name = "freepw"
type = 'javascript'
account_id = ''
usage_model = ''
workers_dev = true
compatibility_date = "2022-04-18"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
